name: DiscordSRV-LinkChannel
version: 1.0.0
main: dev.neonm.linkchannel.DiscordSRVLinkChannelPlugin
api-version: '1.21'
authors: [ neonm ]
depend: [ DiscordSRV ]
commands:
  lcreload:
    description: Reload plugin config
    usage: /lcreload
    permission: linkchannel.reload
permissions:
  linkchannel.reload:
    default: op
